name: Run Newman API Tests
 
on:
  push:
    branches:
      - main  # Runs the tests when changes are pushed to the main branch
  pull_request:
    branches:
      - main  # Runs tests on PRs to main branch
  workflow_dispatch:  # Allows manual trigger from GitHub Actions UI
 
jobs:
  api-test:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
 
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use the latest stable Node.js version
 
      - name: Install Newman
        run: npm install -g newman
 
      - name: Run API Tests with Newman
        run: newman run LearningRESTFULservice.json

      # (Optional) If you want to generate an HTML report
      - name: Run API Tests with HTML Report
        run: |
          npm install -g newman-reporter-html
          newman run LearningRESTFULservice.json -r cli,html --reporter-html-export newman-report.html
 
      # (Optional) Upload report as artifact
      - name: Upload Newman Report
        uses: actions/upload-artifact@v3.1.2
        with:
          name: newman-report
          path: newman-report.html
      
      - name: Verify Report File Exists
        run: ls -l newman-report.html || echo "Report not found!"
  